add isClosed getter
dyedgreen/deno-sqlite pull request #238
Opened 2023-08-13 22:00 UTC by adoublef

This PR is to tackle [this issue](https://github.com/libsql/libsql-client-ts/issues/67), allowing me to make a Deno compatible Turso client that works locally and in a deployed environment.

2023-08-14 07:14 UTC, dyedgreen commented
Overall this looks good! A few minor things:
- The diff seems to have a lot of white space changes, can you try to not re-format the whole file and only add the new function
- Can we add a doc comment, something to the effect of “Indicates if the database handle was previously closed. A closed database handle can no longer be used”
- Can you add some tests (this is pretty simple so something like create a db, assert it’s false, close it, assert it’s true, should be sufficient)

2023-08-14 08:28 UTC, adoublef commented
I have added a test and the jsdocs for the method. Regarding the formatting, I think this is a common problem with my IDE setup so thank you for pointing it out I need to fix it

2023-08-18 17:40 UTC, dyedgreen requested changes

2023-08-18 17:40 UTC, dyedgreen commented on src/db.ts
The `isClosed` function looks good, however there are still lot's of unrelated formatting changes 👀

2023-08-19 19:33 UTC, adoublef commented on src/db.ts
I disabled auto format on my system as I think its just enforcing my coding style on every other project. hopefully that is sorted for you now

2023-08-20 07:53 UTC, dyedgreen commented
Thanks for bearing with me through the review, this looks good to me now! 🚀

2023-08-20 07:54 UTC, dyedgreen approved these changes

2023-08-20 07:55 UTC, merged

2023-08-20 13:05 UTC, adoublef commented
> Thanks for bearing with me through the review, this looks good to me now! 🚀 

No worries, thank you very much as now I think I can get this Turso client for Deno working as a POC!!